version: "3"

services:
  project:
    build: .
    container_name: project
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - project:/project
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  webpacker:
    image: node:latest
    depends_on:
      - project
    environment:
      - NODE_ENV=development
    volumes:
      - ./project:/project
    # ports: # expose webpacker dev server port to app container
    #   - '3035:3035'
    working_dir: /project
    command: npm run watch

volumes:
  project:
