version: "3"

services:
  frontend-backend:
    build: .
    container_name: frontend-backend
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./frontend-backend:/frontend-backend
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

